import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>khana khazana Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          khana khazana Recipes
        </h1>

        <div className={styles.ImgCont}>
          <img className={styles.homeImg} src="/Picture1.jpeg" alt="Bhojan Recipes" width={425} height={283} />
        </div>

        <p className={styles.description}>
          A blog for foodies
        </p>

        <div className="blog">
          <div className="blogItem">
            <h1>Get Delicous Food Recipes</h1>
          </div>
        </div>
      </main>
    </div>
  )
}
